# Generated by Django 6.0 on 2025-12-15 11:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSysteme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('module', models.CharField(help_text="Module de l'ERP concerné", max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('administrateur', 'Administrateur'), ('pharmacien', 'Pharmacien'), ('caissier', 'Caissier'), ('gestionnaire_stock', 'Gestionnaire de stock'), ('livreur', 'Livreur'), ('client', 'Client')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('est_role_systeme', models.BooleanField(default=True, help_text='Rôle prédéfini du système')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('bloque', 'Bloqué'), ('desactive', 'Désactivé')], default='actif', max_length=20)),
                ('raison_statut', models.TextField(blank=True, help_text='Raison de suspension/blocage')),
                ('date_changement_statut', models.DateTimeField(blank=True, null=True)),
                ('otp_secret', models.CharField(blank=True, max_length=32)),
                ('otp_actif', models.BooleanField(default=False)),
                ('tentatives_connexion', models.IntegerField(default=0)),
                ('derniere_tentative', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('ip_derniere_connexion', models.GenericIPAddressField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_commercial', models.CharField(max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacies/logos/')),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordonnée GPS latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordonnée GPS longitude', max_digits=10, null=True)),
                ('telephone_principal', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('site_web', models.URLField(blank=True, null=True)),
                ('numero_autorisation', models.CharField(help_text="Numéro d'autorisation d'exploitation", max_length=100, unique=True)),
                ('nif', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50)),
                ('rccm', models.CharField(blank=True, help_text='Registre de Commerce et du Crédit Mobilier', max_length=50)),
                ('date_autorisation', models.DateField(blank=True, null=True)),
                ('date_expiration_autorisation', models.DateField(blank=True, null=True)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('symbole_devise', models.CharField(default='FCFA', max_length=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.25, help_text='Taux de TVA en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fuseau_horaire', models.CharField(default='Africa/Douala', help_text='Fuseau horaire de la pharmacie', max_length=50)),
                ('horaires_ouverture', models.JSONField(default=dict, help_text="Format: {'lundi': {'ouvert': true, 'debut': '08:00', 'fin': '18:00'}, ...}")),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('fermee', 'Fermée')], default='active', max_length=20)),
                ('configuration_complete', models.BooleanField(default=False)),
                ('pourcentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies_possedees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['nom_commercial'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModificationPharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_modifications', to='gestion_compte.pharmacie')),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modifications',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('navigateur', models.CharField(blank=True, max_length=100)),
                ('systeme_exploitation', models.CharField(blank=True, max_length=100)),
                ('appareil', models.CharField(blank=True, max_length=100)),
                ('succes', models.BooleanField(default=True)),
                ('raison_echec', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
                ('pharmacie', models.ForeignKey(blank=True, help_text='Pharmacie active lors de la connexion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_compte.pharmacie')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pharmacie_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_actifs', to='gestion_compte.pharmacie'),
        ),
        migrations.CreateModel(
            name='MembrePharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('invite', 'Invité')], default='actif', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_retrait', models.DateTimeField(blank=True, null=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to=settings.AUTH_USER_MODEL)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='gestion_compte.pharmacie')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_compte.role')),
            ],
            options={
                'verbose_name': 'Membre de pharmacie',
                'verbose_name_plural': 'Membres de pharmacie',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_compte.permissionsysteme')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='gestion_compte.role')),
            ],
            options={
                'verbose_name': 'Permission de rôle',
                'verbose_name_plural': 'Permissions de rôles',
            },
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['code'], name='gestion_com_code_dfd474_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['proprietaire'], name='gestion_com_proprie_afb4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['statut'], name='gestion_com_statut_47a0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquemodificationpharmacie',
            index=models.Index(fields=['pharmacie', '-date_modification'], name='gestion_com_pharmac_cff1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueconnexion',
            index=models.Index(fields=['utilisateur', '-date_connexion'], name='gestion_com_utilisa_327fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueconnexion',
            index=models.Index(fields=['pharmacie', '-date_connexion'], name='gestion_com_pharmac_749af9_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='gestion_com_email_50d526_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['statut'], name='gestion_com_statut_3e5320_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['pharmacie_active'], name='gestion_com_pharmac_6cd1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='membrepharmacie',
            index=models.Index(fields=['utilisateur', 'pharmacie'], name='gestion_com_utilisa_ef723a_idx'),
        ),
        migrations.AddIndex(
            model_name='membrepharmacie',
            index=models.Index(fields=['pharmacie', 'statut'], name='gestion_com_pharmac_7c30dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membrepharmacie',
            unique_together={('utilisateur', 'pharmacie')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
