# Generated by Django 6.0 on 2025-12-16 08:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20)),
                ('nationalite', models.CharField(default='Camerounaise', max_length=100)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('numero_cni', models.CharField(blank=True, help_text="Numéro de Carte Nationale d'Identité", max_length=50, verbose_name='Numéro CNI')),
                ('photo_cni_recto', models.ImageField(blank=True, null=True, upload_to='documents/cni/', verbose_name='Photo CNI (Recto)')),
                ('photo_cni_verso', models.ImageField(blank=True, null=True, upload_to='documents/cni/', verbose_name='Photo CNI (Verso)')),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('diplome', models.CharField(blank=True, max_length=200)),
                ('specialite', models.CharField(blank=True, max_length=200)),
                ('numero_ordre', models.CharField(blank=True, help_text="Numéro d'ordre professionnel (pour pharmaciens)", max_length=100)),
                ('annees_experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('contact_urgence_relation', models.CharField(blank=True, help_text='Ex: Époux/Épouse, Parent, Ami, etc.', max_length=100)),
                ('theme', models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre')], default='clair', max_length=20)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=10)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_sms', models.BooleanField(default=False)),
                ('notifications_push', models.BooleanField(default=True)),
                ('nom_banque', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_compte', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('biographie', models.TextField(blank=True, help_text='Courte biographie ou présentation', max_length=1000)),
                ('notes_internes', models.TextField(blank=True, help_text='Notes visibles uniquement par les administrateurs')),
                ('score_points', models.IntegerField(default=0)),
                ('niveau', models.IntegerField(default=1)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('profil_complet', models.BooleanField(default=False)),
                ('pourcentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur'], name='gestion_com_utilisa_a3d12d_idx'), models.Index(fields=['numero_ordre'], name='gestion_com_numero__130eb3_idx')],
            },
        ),
    ]
