# Generated by Django 6.0 on 2026-01-12 16:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_compte', '0002_profilutilisateur'),
        ('gestion_vente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_number', models.CharField(max_length=50, verbose_name='Numéro de caisse')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Fond de caisse d'ouverture")),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Solde actuel')),
                ('expected_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Solde attendu')),
                ('is_open', models.BooleanField(default=False, verbose_name='Caisse ouverte')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouverte le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fermée le')),
                ('total_sales_count', models.IntegerField(default=0, verbose_name='Nombre de ventes')),
                ('total_cash_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total espèces reçues')),
                ('total_change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total monnaie rendue')),
                ('opening_notes', models.TextField(blank=True, verbose_name="Notes d'ouverture")),
                ('closing_notes', models.TextField(blank=True, verbose_name='Notes de fermeture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_register_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='gestion_compte.pharmacie', verbose_name='Pharmacie')),
            ],
            options={
                'verbose_name': 'Caisse enregistreuse',
                'verbose_name_plural': 'Caisses enregistreuses',
                'db_table': 'sales_cash_registers',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_type', models.CharField(choices=[('opening', "Comptage d'ouverture"), ('closing', 'Comptage de fermeture'), ('intermediate', 'Comptage intermédiaire')], max_length=20, verbose_name='Type de comptage')),
                ('bill_10000', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billets de 10 000')),
                ('bill_5000', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billets de 5 000')),
                ('bill_2000', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billets de 2 000')),
                ('bill_1000', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Billets de 1 000')),
                ('coin_500', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 500')),
                ('coin_250', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 250')),
                ('coin_200', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 200')),
                ('coin_100', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 100')),
                ('coin_50', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 50')),
                ('coin_25', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 25')),
                ('coin_10', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 10')),
                ('coin_5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pièces de 5')),
                ('total_counted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total compté')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant attendu')),
                ('discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Écart entre le montant compté et le montant attendu', max_digits=10, verbose_name='Écart')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('count_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du comptage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts_performed', to=settings.AUTH_USER_MODEL, verbose_name='Compté par')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts_verified', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='gestion_vente.cashregister', verbose_name='Caisse')),
            ],
            options={
                'verbose_name': 'Comptage de caisse',
                'verbose_name_plural': 'Comptages de caisse',
                'db_table': 'sales_cash_counts',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Vente'), ('refund', 'Remboursement'), ('cash_in', 'Entrée de fonds'), ('cash_out', 'Sortie de fonds'), ('opening', 'Ouverture de caisse'), ('closing', 'Fermeture de caisse')], max_length=20, verbose_name='Type de transaction')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant dû (prix total)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant à payer')),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant remis par le client', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Somme versée')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monnaie à rendre (calculé automatiquement)', max_digits=10, verbose_name='Monnaie à rendre')),
                ('change_breakdown', models.JSONField(default=dict, help_text='Détail des billets et pièces pour la monnaie', verbose_name='Détail de la monnaie')),
                ('payment_method', models.CharField(default='cash', help_text='Méthode de paiement (cash par défaut)', max_length=20, verbose_name='Méthode de paiement')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gestion_vente.cashregister', verbose_name='Caisse')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_processed', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='gestion_vente.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Transaction de caisse',
                'verbose_name_plural': 'Transactions de caisse',
                'db_table': 'sales_cash_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ChangeShortage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denomination', models.CharField(help_text='Dénomination manquante (ex: 500, 1000)', max_length=20, verbose_name='Dénomination')),
                ('quantity_needed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité nécessaire')),
                ('quantity_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité disponible')),
                ('shortage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant du manque')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_shortages', to='gestion_vente.cashregister', verbose_name='Caisse')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_shortages_reported', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Manque de monnaie',
                'verbose_name_plural': 'Manques de monnaie',
                'db_table': 'sales_change_shortages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['pharmacie', '-opened_at'], name='sales_cash__pharmac_a60912_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['cashier', '-opened_at'], name='sales_cash__cashier_517e12_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['is_open'], name='sales_cash__is_open_50985b_idx'),
        ),
        migrations.AddIndex(
            model_name='cashcount',
            index=models.Index(fields=['cash_register', '-count_date'], name='sales_cash__cash_re_651b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashcount',
            index=models.Index(fields=['count_type', '-count_date'], name='sales_cash__count_t_920662_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['cash_register', '-transaction_date'], name='sales_cash__cash_re_99bc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['sale'], name='sales_cash__sale_id_83cb55_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_type', '-transaction_date'], name='sales_cash__transac_d34eff_idx'),
        ),
        migrations.AddIndex(
            model_name='changeshortage',
            index=models.Index(fields=['cash_register', 'is_resolved'], name='sales_chang_cash_re_9812ff_idx'),
        ),
    ]
